//app reset
export const RESET_APP = 'RESET_APP';

//accounts
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const ADD_ACCOUNTS = "ADD_ACCOUNTS";
export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";

//legacy account
export const ADD_LEGACY_ACCOUNT = "ADD_LEGACY_ACCOUNT";
export const ADD_LEGACY_ACCOUNTS = "ADD_LEGACY_ACCOUNTS";
export const REMOVE_LEGACY_ACCOUNT = "REMOVE_LEGACY_ACCOUNT";

//active_account
export const ADD_ACTIVE_ACCOUNT = "ADD_ACTIVE_ACCOUNT";

//wallet_exists
export const WALLET_EXISTS = "WALLET_EXISTS";

//legacy_wallet
export const ADD_LEGACY_WALLET = 'ADD_LEGACY_WALLET';
export const REMOVE_LEGACY_WALLET = 'REMOVE_LEGACY_WALLET';
export const ADD_LEGACY_BALANCE = "ADD_LEGACY_BALANCE";
export const REMOVE_LEGACY_BALANCE = "REMOVE_LEGACY_BALANCE";
export const ADD_LEGACY_BTC_BALANCE = "ADD_LEGACY_BTC_BALANCE";
export const REMOVE_LEGACY_BTC_BALANCE = "REMOVE_LEGACY_BTC_BALANCE";
export const ADD_LEGACY_BALANCE_PENDING = "ADD_LEGACY_BALANCE_PENDING";
export const REMOVE_LEGACY_BALANCE_PENDING = "REMOVE_LEGACY_BALANCE_PENDING";
export const ADD_LEGACY_BTC_BALANCE_PENDING = "ADD_LEGACY_BTC_BALANCE_PENDING";
export const REMOVE_LEGACY_BTC_BALANCE_PENDING = "REMOVE_LEGACY_BTC_BALANCE_PENDING";
export const RESET_LEGACY_BALANCE = "RESET_LEGACY_BALANCE";
export const RESET_LEGACY_BTC_BALANCE = "RESET_LEGACY_BTC_BALANCE";
export const RESET_LEGACY_BALANCE_PENDING = "RESET_LEGACY_BALANCE_PENDING";
export const RESET_LEGACY_BTC_BALANCE_PENDING = "RESET_LEGACY_BTC_BALANCE_PENDING";
export const RESET_ALL_BALANCES = "RESET_ALL_BALANCES";
export const REPLACE_LEGACY_KEY = "REPLACE_LEGACY_KEY";
export const REPLACE_LEGACY_ACCOUNTS = "REPLACE_LEGACY_ACCOUNTS";


//wizard
export const ADD_WIZARD_STEP = "ADD_WIZARD_STEP";
export const REMOVE_WIZARD_STEP = "REMOVE_WIZARD_STEP";
export const RESET_WIZARD_STEP = "RESET_WIZARD_STEP";
export const ADD_WIZARD_DATA = "ADD_WIZARD_DATA";
export const REMOVE_WIZARD_DATA = "REMOVE_WIZARD_DATA";
export const RESET_WIZARD_DATA = "RESET_WIZARD_DATA";
export const ADD_WIZARD_ERRORS = "ADD_WIZARD_ERRORS";
export const REMOVE_WIZARD_ERRORS = "REMOVE_WIZARD_ERRORS";
export const RESET_WIZARD_ERRORS = "RESET_WIZARD_ERRORS";
export const ADD_WIZARD_TOUCHED = "ADD_WIZARD_TOUCHED";
export const REMOVE_WIZARD_TOUCHED = "REMOVE_WIZARD_TOUCHED";
export const RESET_WIZARD_TOUCHED = "RESET_WIZARD_TOUCHED";

export const INIT_WIZARD_DATA = "INIT_WIZARD_DATA";
export const INIT_WIZARD_ERRORS = "INIT_WIZARD_ERRORS";
export const INIT_WIZARD_TOUCHED = "INIT_WIZARD_TOUCHED";

//error
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

//language
export const CHANGE_LANG = "CHANGE_LANG";

//contacts
export const ADD_CONTACTS = "ADD_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const RESET_NEW_CONTACT = "INIT_NEW_CONTACT";
export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
export const ADD_CONTACT_COUNTER = "ADD_CONTACT_COUNTER";
export const ADD_CONTACT_TOUCHED = "ADD_CONTACT_TOUCHED";
export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";


//home-history
export const ADD_ACCOUNT_HISTORY = "ADD_ACCOUNT_HISTORY";
export const RESET_ACCOUNT_HISTORY = "RESET_ACCOUNT_HISTORY";

export const HOME_MODAL = "HOME_MODAL";
export const ACCOUNT_LABELS = "ACCOUNT_LABELS";

export const ADD_DAEMON_HOST = "ADD_DAEMON_HOST";
export const ADD_DAEMON_PORT = "ADD_DAEMON_PORT";
export const ADD_DAEMON_MODAL = "ADD_DAEMON_MODAL";

export const ADD_ACTIVE_TAB = "ADD_ACTIVE_TAB";

