//app reset
const RESET_APP = 'RESET_APP';

//accounts
const ADD_ACCOUNT = "ADD_ACCOUNT";
const ADD_ACCOUNTS = "ADD_ACCOUNTS";
const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";

//legacy account
const ADD_LEGACY_ACCOUNT = "ADD_LEGACY_ACCOUNT";
const ADD_LEGACY_ACCOUNTS = "ADD_LEGACY_ACCOUNTS";
const REMOVE_LEGACY_ACCOUNT = "REMOVE_LEGACY_ACCOUNT";

//active_account
const ADD_ACTIVE_ACCOUNT = "ADD_ACTIVE_ACCOUNT";

//wallet_exists
const WALLET_EXISTS = "WALLET_EXISTS";

//legacy_wallet
const ADD_LEGACY_WALLET = 'ADD_LEGACY_WALLET';
const REMOVE_LEGACY_WALLET = 'REMOVE_LEGACY_WALLET';

//legacy_wizard
const ADD_LEGACY_WIZARD_STEP = 'ADD_LEGACY_WIZARD_STEP';
const REMOVE_LEGACY_WIZARD_STEP = 'REMOVE_LEGACY_WIZARD_STEP';
const RESET_LEGACY_WIZARD_STEP = 'RESET_LEGACY_WIZARD_STEP';
const ADD_LEGACY_WIZARD_DATA = 'ADD_LEGACY_WIZARD_DATA';
const REMOVE_LEGACY_WIZARD_DATA = 'REMOVE_LEGACY_WIZARD_DATA';
const RESET_LEGACY_WIZARD_DATA = 'RESET_LEGACY_WIZARD_DATA';
const ADD_LEGACY_WIZARD_ERRORS = 'ADD_LEGACY_WIZARD_ERRORS';
const REMOVE_LEGACY_WIZARD_ERRORS = 'REMOVE_LEGACY_WIZARD_ERRORS';
const RESET_LEGACY_WIZARD_ERRORS = 'RESET_LEGACY_WIZARD_ERRORS';
const ADD_LEGACY_WIZARD_TOUCHED = 'ADD_LEGACY_WIZARD_TOUCHED';
const REMOVE_LEGACY_WIZARD_TOUCHED = 'REMOVE_LEGACY_WIZARD_TOUCHED';
const RESET_LEGACY_WIZARD_TOUCHED = 'RESET_LEGACY_WIZARD_TOUCHED';

//create_wizard
const ADD_CREATE_WIZARD_STEP = 'ADD_CREATE_WIZARD_STEP';
const REMOVE_CREATE_WIZARD_STEP = 'REMOVE_CREATE_WIZARD_STEP';
const RESET_CREATE_WIZARD_STEP = 'RESET_CREATE_WIZARD_STEP';
const ADD_CREATE_WIZARD_DATA = 'ADD_CREATE_WIZARD_DATA';
const REMOVE_CREATE_WIZARD_DATA = 'REMOVE_CREATE_WIZARD_DATA';
const RESET_CREATE_WIZARD_DATA = 'RESET_CREATE_WIZARD_DATA';

//open_wizard
const ADD_OPEN_WIZARD_STEP = 'ADD_OPEN_WIZARD_STEP';
const REMOVE_OPEN_WIZARD_STEP = 'REMOVE_OPEN_WIZARD_STEP';
const RESET_OPEN_WIZARD_STEP = 'RESET_OPEN_WIZARD_STEP';
const ADD_OPEN_WIZARD_DATA = 'ADD_OPEN_WIZARD_DATA';
const REMOVE_OPEN_WIZARD_DATA = 'REMOVE_OPEN_WIZARD_DATA';
const RESET_OPEN_WIZARD_DATA = 'RESET_OPEN_WIZARD_DATA';
const ADD_OPEN_WIZARD_ERRORS = 'ADD_OPEN_WIZARD_ERRORS';
const REMOVE_OPEN_WIZARD_ERRORS = 'REMOVE_OPEN_WIZARD_ERRORS';
const RESET_OPEN_WIZARD_ERRORS = 'RESET_OPEN_WIZARD_ERRORS';
const ADD_OPEN_WIZARD_TOUCHED = 'ADD_OPEN_WIZARD_TOUCHED';
const REMOVE_OPEN_WIZARD_TOUCHED = 'REMOVE_OPEN_WIZARD_TOUCHED';
const RESET_OPEN_WIZARD_TOUCHED = 'RESET_OPEN_WIZARD_TOUCHED';

//restore_wizard
const ADD_RESTORE_WIZARD_STEP = "ADD_RESTORE_WIZARD_STEP";
const REMOVE_RESTORE_WIZARD_STEP = "REMOVE_RESTORE_WIZARD_STEP";
const RESET_RESTORE_WIZARD_STEP = "RESET_RESTORE_WIZARD_STEP";
const ADD_RESTORE_WIZARD_DATA = "ADD_RESTORE_WIZARD_DATA";
const REMOVE_RESTORE_WIZARD_DATA = "REMOVE_RESTORE_WIZARD_DATA";
const RESET_RESTORE_WIZARD_DATA = "RESET_RESTORE_WIZARD_DATA";
const ADD_RESTORE_WIZARD_ERRORS = "ADD_RESTORE_WIZARD_ERRORS";
const REMOVE_RESTORE_WIZARD_ERRORS = "REMOVE_RESTORE_WIZARD_ERRORS";
const RESET_RESTORE_WIZARD_ERRORS = "RESET_RESTORE_WIZARD_ERRORS";
const ADD_RESTORE_WIZARD_TOUCHED = "ADD_RESTORE_WIZARD_TOUCHED";
const REMOVE_RESTORE_WIZARD_TOUCHED = "REMOVE_RESTORE_WIZARD_TOUCHED";
const RESET_RESTORE_WIZARD_TOUCHED = "RESET_RESTORE_WIZARD_TOUCHED";

const INIT_RESTORE_WIZARD_DATA = "INIT_RESTORE_WIZARD_DATA";
const INIT_RESTORE_WIZARD_ERRORS = "INIT_RESTORE_WIZARD_ERRORS";
const INIT_RESTORE_WIZARD_TOUCHED = "INIT_RESTORE_WIZARD_TOUCHED";

//error
const ADD_ERROR = "ADD_ERROR";
const REMOVE_ERROR = "REMOVE_ERROR";

//language
const CHANGE_LANG = "CHANGE_LANG";


export {
    RESET_APP,
    ADD_ACCOUNT,
    ADD_ACCOUNTS,
    REMOVE_ACCOUNT,
    ADD_LEGACY_ACCOUNT,
    ADD_LEGACY_ACCOUNTS,
    REMOVE_LEGACY_ACCOUNT,
    ADD_ACTIVE_ACCOUNT,
    WALLET_EXISTS,
    ADD_LEGACY_WALLET,
    REMOVE_LEGACY_WALLET,
    ADD_ERROR,
    REMOVE_ERROR,
    CHANGE_LANG,
    //legacy_wizard
    ADD_LEGACY_WIZARD_STEP,
    REMOVE_LEGACY_WIZARD_STEP,
    RESET_LEGACY_WIZARD_STEP,
    ADD_LEGACY_WIZARD_DATA,
    REMOVE_LEGACY_WIZARD_DATA,
    RESET_LEGACY_WIZARD_DATA,
    ADD_LEGACY_WIZARD_ERRORS,
    REMOVE_LEGACY_WIZARD_ERRORS,
    RESET_LEGACY_WIZARD_ERRORS,
    ADD_LEGACY_WIZARD_TOUCHED,
    REMOVE_LEGACY_WIZARD_TOUCHED,
    RESET_LEGACY_WIZARD_TOUCHED,
    //create_wizard
    ADD_CREATE_WIZARD_STEP,
    REMOVE_CREATE_WIZARD_STEP,
    RESET_CREATE_WIZARD_STEP,
    ADD_CREATE_WIZARD_DATA,
    REMOVE_CREATE_WIZARD_DATA,
    RESET_CREATE_WIZARD_DATA,
    //open_wizard
    ADD_OPEN_WIZARD_STEP,
    REMOVE_OPEN_WIZARD_STEP,
    RESET_OPEN_WIZARD_STEP,
    ADD_OPEN_WIZARD_DATA,
    REMOVE_OPEN_WIZARD_DATA,
    RESET_OPEN_WIZARD_DATA,
    ADD_OPEN_WIZARD_ERRORS,
    REMOVE_OPEN_WIZARD_ERRORS,
    RESET_OPEN_WIZARD_ERRORS,
    ADD_OPEN_WIZARD_TOUCHED,
    REMOVE_OPEN_WIZARD_TOUCHED,
    RESET_OPEN_WIZARD_TOUCHED,
    //restore_wizard
    ADD_RESTORE_WIZARD_STEP,
    REMOVE_RESTORE_WIZARD_STEP,
    RESET_RESTORE_WIZARD_STEP,
    ADD_RESTORE_WIZARD_DATA,
    REMOVE_RESTORE_WIZARD_DATA,
    RESET_RESTORE_WIZARD_DATA,
    ADD_RESTORE_WIZARD_ERRORS,
    REMOVE_RESTORE_WIZARD_ERRORS,
    RESET_RESTORE_WIZARD_ERRORS,
    ADD_RESTORE_WIZARD_TOUCHED,
    REMOVE_RESTORE_WIZARD_TOUCHED,
    RESET_RESTORE_WIZARD_TOUCHED,
    
    INIT_RESTORE_WIZARD_DATA,
    INIT_RESTORE_WIZARD_ERRORS,
    INIT_RESTORE_WIZARD_TOUCHED
}