export default {
    0:"OK",
    1:"ERR_READ_REQ",
    2:"ERR_JSON_REQ_MAL",
    3:"ERR_JSON_RES_MAL",
    "EMPTY_PASSWORD":"EMPTY_PASSWORD",
    'FILE_NOT_SELECTED':'FILE_NOT_SELECTED',
    'FILE_NOT_VALID':'FILE_NOT_VALID'
}